version: '3.7'

services:
  trading-postgres:
    image: "postgres:10.5"
    container_name: "trading-postgres-db"
    environment:
      POSTGRES_DB: "trading-postgres-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
