server:
  port: 9087

spring:
  application:
    name: socket-trading-event-pusher
  main:
    allow-bean-definition-overriding: true

kafka:
  bootstrap:
    server: localhost:9092

trading:
  init:
    topics: socket-trading-event-notification-topic







